version: '3.8'

services:
  smoothy-server:
    build: ./server
    ports:
      - "4001:4000"
    volumes:
      - ./server/uploads:/usr/src/app/uploads
      - ./server/outputs:/usr/src/app/outputs
    environment:
      - NODE_ENV=production
      - CORS_ORIGIN=https://smoothy.mercerwest.com,https://mercerwest.com
    restart: unless-stopped
    networks:
      - smoothy-network

  smoothy-frontend:
    build:
      context: .
      args:
        VITE_SERVER_URL: http://3.131.97.110:4001
    ports:
      - "3000:80"
    environment:
      - VITE_SERVER_URL=http://3.131.97.110:4001
    depends_on:
      - smoothy-server
    restart: unless-stopped
    networks:
      - smoothy-network

networks:
  smoothy-network:
    driver: bridge 